### ISSUE TITLE
simplified scripts for corpus statistic collection

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#128]
We have already many corpora and calling all the commands to gather the statistics manually is cumbersome. We should have one bash script per statistic that calls the command for all the datasets.

But first, let's collect the commands that we used so far in the issue. EDIT: See the list below.

**Comment by idalr** [comment]
Here are lists of commands I have put together. There might possibly be bugs due to recent changes, as I haven't rerun everything.

# count entity labels
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_entity_labels metric.labels=[MajorClaim,Claim,Premise] +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=count_entity_labels metric.labels=[MajorClaim,Claim,Premise] dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=count_entity_labels metric.labels=[opp,pro] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=count_entity_labels metric.labels=[fact,policy,reference,testimony,value] +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=count_entity_labels metric.labels=[background_claim,own_claim,data] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=count_entity_labels metric.labels=[proposal,assertion,result,observation,means,description] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# count relation labels
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_entity_labels metric.field=relations metric.labels=[supports,attacks] +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric.field=relations metric.labels=[Support,Partial-Attack,Attack] dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=count_entity_labels metric.field=relations +metric.labels=[seq,sup,exa,add,reb,und,joint] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=count_entity_labels metric.field=relations metric.labels=[reason,evidence] +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=count_entity_labels metric.field=relations metric.labels=[supports,contradicts,semantically_same] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=count_entity_labels metric.field=relations metric.labels=[support,attack,detail,sequence,additional] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# count text tokens
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_text_tokens +dataset.create_validation_split._enabled_=false 

python src/evaluate_documents.py dataset=abstrct_prepared metric=count_text_tokens dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=count_text_tokens +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=count_text_tokens +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=count_text_tokens +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=count_text_tokens +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# count text characters
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_text_characters +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=count_text_characters dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=count_text_characters +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=count_text_characters +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=count_text_characters +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=count_text_characters +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# count relation argument distances
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_relation_argument_distances +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=count_relation_argument_distances dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=count_relation_argument_distances +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=count_relation_argument_distances +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=count_relation_argument_distances +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=count_relation_argument_distances +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# count relation argument token distances
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_relation_argument_token_distances +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=count_relation_argument_token_distances dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=metric=count_relation_argument_token_distances +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=count_relation_argument_token_distances +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=count_relation_argument_token_distances +metric.tokenize_kwargs.strict_span_conversion=false +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=count_relation_argument_token_distances +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# span length characters
```
python src/evaluate_documents.py dataset=aae2_prepared metric=span_lengths_characters +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=span_lengths_characters dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=span_lengths_characters +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=span_lengths_characters +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=span_lengths_characters +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=span_lengths_characters +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# span length characters with entity labels
```
python src/evaluate_documents.py dataset=aae2_prepared metric=span_lengths_characters metric.labels=[MajorClaim,Claim,Premise] +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=span_lengths_characters metric.labels=[MajorClaim,Claim,Premise] dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=span_lengths_characters metric.labels=[opp,pro] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=span_lengths_characters metric.labels=[fact,policy,reference,testimony,value] +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=span_lengths_characters metric.labels=[background_claim,own_claim,data] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=span_lengths_characters metric.labels=[proposal,assertion,result,observation,means,description] +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

# span lengths tokens
```
python src/evaluate_documents.py dataset=aae2_prepared metric=span_lengths_tokens +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=abstrct_prepared metric=span_lengths_tokens dataset.rename_splits=false +dataset.keep_other_splits=true

python src/evaluate_documents.py dataset=argmicro_prepared metric=span_lengths_tokens +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=cdcp_prepared metric=span_lengths_tokens +dataset.create_validation_split._enabled_=false

python src/evaluate_documents.py dataset=sciarg_prepared metric=span_lengths_tokens +metric.tokenize_kwargs.strict_span_conversion=false +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false

python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=span_lengths_tokens +dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false
```

**Comment by ArneBinder** [comment]
Some of these commands should now work with all datasets at once when using the branch from #129, but it requires to set `+hydra.callbacks.save_job_return.integrate_multirun_result=false`. The following metrics should work:
 - [x] `count_entity_labels`
 - [x] `count_relation_argument_distances`
 - [x] `count_relation_argument_token_distances`
 - [x] `count_relation_labels`
 - [x] `count_text_characters`
 - [x] `count_text_tokens`
 - [x] `span_lengths_characters`
 - [x] `span_lengths_characters_per_label`
 - [x] `span_lengths_tokens`

The issue regarding label based metrics will be hopefully fixed by #130.

Then, the final commands should be sth like:
```
python src/evaluate_documents.py \
metric=METRIC \
dataset=aae2_base,abstrct_base,argmicro_base,cdcp_base,sciarg_base,scidtb_argmin_base \
+hydra.callbacks.save_job_return.integrate_multirun_result=false \
--multirun
```
When executing the above, you should see sth like this at the end of the output on the console:
```
...
[2023-09-14 19:28:57,953][HYDRA] Saving job_return in /home/arbi01/projects/pie-document-level/logs/document_evaluation/multiruns/default/2023-09-14_19-28-43/job_return_value.json
[2023-09-14 19:28:57,953][HYDRA] Saving job_return in /home/arbi01/projects/pie-document-level/logs/document_evaluation/multiruns/default/2023-09-14_19-28-43/job_return_value.md
``` 
The paths point to files that contain the combined output of all the commands.

**Comment by idalr** [comment]
I tested with all the metrics above and compared the results when running without `hydra`'s `multirun`. Most metrics were fine, except `count_relation_argument_token_distances` and `span_lengths_tokens` in `cdcp` and `sciarg`. The error I got was 
```
ValueError: cannot find token span for character span:...
```

<details>
<summary>Here is the full error</summary>

when running this

```
python src/evaluate_documents.py metric=count_relation_argument_token_distances dataset=aae2_base,abstrct_base,argmicro_base,cdcp_base,sciarg_base,scidtb_argmin_base  +hydra.callbacks.save_job_return.integrate_multirun_result=false --multirun
```

I encountered this error:

```
Error executing job with overrides: ['metric=count_relation_argument_token_distances', 'dataset=cdcp_base']
Traceback (most recent call last):
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\src\evaluate_documents.py", line 107, in main
    metric_dict, _ = evaluate_documents(cfg)
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\src\utils\task_utils.py", line 42, in wrap
    raise ex
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\src\utils\task_utils.py", line 39, in wrap
    task_result = task_func(cfg=cfg)
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\src\evaluate_documents.py", line 98, in evaluate_documents
    metric_dict = metric(documents)
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\env\lib\site-packages\pytorch_ie\core\metric.py", line 40, in __call__
    split_values: T = self(split)  # type: ignore
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\env\lib\site-packages\pytorch_ie\core\metric.py", line 50, in __call__
    self._update(doc)
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\env\lib\site-packages\pytorch_ie\core\statistic.py", line 183, in _update
    values = self._collect(document)
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\src\metrics\statistics.py", line 63, in _collect
    docs = tokenize_document(
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\env\lib\site-packages\pytorch_ie\data\document_conversion.py", line 270, in tokenize_document
    tokenized_document = text_based_document_to_token_based(
  File "C:\Users\Rinrada\PycharmProjects\pie-document-level\env\lib\site-packages\pytorch_ie\data\document_conversion.py", line 106, in text_based_document_to_token_based
    raise ValueError(
ValueError: cannot find token span for character span: " For example, when a person who allegedly owes a debt is told to come to court on a work day
, they may be forced to choose between a default judgment and their job.", text="State and local court rules sometimes make default judgments much m
ore likely. For example, when a person who allegedly owes a debt is told to come to court on a work day, they may be forced to choose between a defa
ult judgment and their job. I urge the CFPB to find practices that involve scheduling hearings at inconvenient times unfair, deceptive, and abusive,
 or inconsistent with 1692i.", token_offset_mapping=[(0, 0), (0, 5), (6, 9), (10, 15), (16, 21), (22, 27), (28, 37), (38, 42), (43, 50), (51, 60), (
61, 65), (66, 70), (71, 77), (77, 78), (79, 82), (83, 90), (90, 91), (92, 96), (97, 98), (99, 105), (106, 109), (110, 119), (120, 124), (125, 126), 
(127, 131), (132, 134), (135, 139), (140, 142), (143, 147), (148, 150), (151, 156), (157, 159), (160, 161), (162, 166), (167, 170), (170, 171), (172
, 176), (177, 180), (181, 183), (184, 190), (191, 193), (194, 200), (201, 208), (209, 210), (211, 218), (219, 227), (228, 231), (232, 237), (238, 24
1), (241, 242), (243, 244), (245, 249), (250, 253), (254, 256), (256, 257), (257, 258), (259, 261), (262, 266), (267, 276), (277, 281), (282, 289), 
(290, 300), (301, 309), (310, 312), (313, 316), (316, 318), (318, 321), (321, 325), (326, 331), (332, 338), (338, 339), (340, 343), (343, 349), (349, 350), (351, 354), (355, 362), (362, 363), (364, 366), (367, 379), (380, 384), (385, 389), (389, 390), (390, 391), (0, 0)]

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

</details>

I've also looked into it a bit. I thought the issue might come from `tokenized_document_type`, but when I changed that, it didn't really fix the error.

**Comment by ArneBinder** [comment]
Since #130 is merged now and all statistics can be calculated with the command mentioned in [the above comment](https://github.com/ArneBinder/pie-document-level/issues/128#issuecomment-1719861711), we can close this. #145 is the follow-up.
